#ifndef __vtkWindow__
#define __vtkWindow__

/**
@file
Subclass of mainWindow, which is generated by wxFormBuilder.
*/

#include "wx-ebsd.h"

/** Implementing mainWindow */
class vtkWindow : public mainWindow
{
public:
	/** Constructor */
	vtkWindow( wxWindow* parent );
};

#endif // __vtkWindow__
