#ifndef __open-ebsdfilterDialogUI__
#define __open-ebsdfilterDialogUI__

/**
@file
Subclass of filterDialogUI, which is generated by wxFormBuilder.
*/

#include "wx-ebsd.h"

/** Implementing filterDialogUI */
class open-ebsdfilterDialogUI : public filterDialogUI
{
protected:
	// Handlers for filterDialogUI events.
	void OnOK( wxCommandEvent& event );
	
public:
	/** Constructor */
	open-ebsdfilterDialogUI( wxWindow* parent );
};

#endif // __open-ebsdfilterDialogUI__
