#ifndef __open-ebsdalignmentFrameUI__
#define __open-ebsdalignmentFrameUI__

/**
@file
Subclass of alignmentFrameUI, which is generated by wxFormBuilder.
*/

#include "wx-ebsd.h"

/** Implementing alignmentFrameUI */
class open-ebsdalignmentFrameUI : public alignmentFrameUI
{
protected:
	// Handlers for alignmentFrameUI events.
	void Init( wxActivateEvent& event );
	void sliceSelected( wxCommandEvent& event );
	void UpdateSlice( wxScrollEvent& event );
	void OnCancel( wxCommandEvent& event );
	void OnOK( wxCommandEvent& event );
	
public:
	/** Constructor */
	open-ebsdalignmentFrameUI( wxWindow* parent );
};

#endif // __open-ebsdalignmentFrameUI__
