#ifndef __open-ebsddilateDialogUI__
#define __open-ebsddilateDialogUI__

/**
@file
Subclass of dilateDialogUI, which is generated by wxFormBuilder.
*/

#include "wx-ebsd.h"

/** Implementing dilateDialogUI */
class open-ebsddilateDialogUI : public dilateDialogUI
{
protected:
	// Handlers for dilateDialogUI events.
	void OnOK( wxCommandEvent& event );
	
public:
	/** Constructor */
	open-ebsddilateDialogUI( wxWindow* parent );
};

#endif // __open-ebsddilateDialogUI__
