#ifndef __open-ebsdfileInfoDialogUI__
#define __open-ebsdfileInfoDialogUI__

/**
@file
Subclass of fileInfoDialogUI, which is generated by wxFormBuilder.
*/

#include "wx-ebsd.h"

/** Implementing fileInfoDialogUI */
class fileInfoDialog : public fileInfoDialogUI
{
protected:
	// Handlers for fileInfoDialogUI events.
	void CheckValues( wxCommandEvent& event );
	
public:
	/** Constructor */
	fileInfoDialog( wxWindow* parent );
};

#endif // __open-ebsdfileInfoDialogUI__
